name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag myns75/tp_cd

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -ac -screen 0 1024x768x8 &

      - name: Start Flask app in the background
        run: python app.py &

      - name: Print debugging information
        run: |
          echo "Checking available display servers:"
          xdpyinfo -display :99 || true

      - name: Run Selenium tests
        run: |
          # Set up Selenium container and run tests
          docker run --network host --rm -e DISPLAY=:99 selenium/standalone-chrome python -m unittest test_e2e_app.py
          docker run --network host --rm -e DISPLAY=:99 selenium/standalone-chrome python -m unittest test-app.py

      - name: Stop the Flask app
        run: pkill -f "python app.py"

      - name: Push Docker image
        run: |
          docker push myns75/tp_cd
