name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    services: 
      selenium:
        image: selenium/standalone-firefox
        ports:
          - 4444:4444
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Selenium image with Chrome
        run: docker pull selenium/node-firefox

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag myns75/tp_cd

      - name: Start Flask app and run tests in Docker container
        run: |
          docker run -d --name my-container myns75/tp_cd

          sleep 5

          docker exec my-container python -m unittest test_e2e_app.py
          docker exec my-container python -m unittest test-app.py

          docker stop my-container
          docker rm my-container

      - name: Push Docker image
        run: docker push myns75/tp_cd
